// src/views/system/role-assign/data.tsx
import type { User } from '@/api/system/user/model';
import type { VxeGridProps } from 'vxe-table';

import { UserInfoCell } from '@/components';

export const columns: VxeGridProps['columns'] = [
  {
    type: 'checkbox',
    width: 45,
    align: 'center',
    resizable: false,
  },
  {
    title: '用户账号',
    field: 'userName',
    minWidth: 120,
  },
  {
    title: '用户信息',
    field: 'nickName',
    align: 'left',
    minWidth: 200,
    slots: {
      default: ({ row }: { row: User }) => {
        return (
          <UserInfoCell
            avatar={row.avatar}
            subtitle={row.phoneNumber}
            title={row.nickName}
          />
        );
      },
    },
  },
];

// src/components/tree/src/data.tsx
import type { ID } from '@/api/common';
import type { MenuOption } from '@/api/system/menu/model';
import type { VxeGridProps } from 'vxe-table';

import { h } from 'vue';

import { VbenIcon } from '@/icons';
import { menuTypes } from '@/views/system/menu/data';

export interface Permission {
  checked: boolean;
  id: ID;
  label: string;
}

export interface MenuPermissionOption extends MenuOption {
  permissions: Permission[];
}

export const nodeOptions = [
  { label: '节点关联', value: true },
  { label: '节点独立', value: false },
];

export const columns: VxeGridProps['columns'] = [
  {
    type: 'checkbox',
    title: '菜单名称',
    field: 'label',
    treeNode: true,
    headerAlign: 'left',
    align: 'left',
    width: 230,
  },
  {
    title: '图标',
    field: 'icon',
    width: 80,
    slots: {
      default: ({ row }) => {
        if (row?.icon === '#') {
          return '';
        }
        return (
          <span class={'flex justify-center'}>
            <VbenIcon icon={row.icon} />
          </span>
        );
      },
    },
  },
  {
    title: '类型',
    field: 'menuType',
    width: 80,
    slots: {
      default: ({ row }) => {
        const current = menuTypes[row.menuType as 'C' | 'F' | 'M'];
        if (!current) {
          return '未知';
        }
        return (
          <span class="flex items-center justify-center gap-1">
            {h(current.icon, { class: 'size-[18px]' })}
            <span>{current.value}</span>
          </span>
        );
      },
    },
  },
  {
    title: '权限标识',
    field: 'permissions',
    headerAlign: 'left',
    align: 'left',
    slots: {
      default: 'permissions',
    },
  },
];
